### ISSUE TITLE
Application label causing manifest merger issues

### ISSUE THREAD

**Issue by kyhule** [btkelly/gandalf#61] opened 2016-08-15 20:08 UTC
Gradle is failing when trying to merge manifest files. I try to use the replace attribute as suggested but it does not work. Have you come across this at all? What is the purpose of the label being defined in your library's manifest? Comparing to other popular third-party android libraries, the label attribute is not usually defined in the library manifest.

Attribute application@label value=(ClinicalKey DEBUG) from AndroidManifest.xml:20:9-41
	is also present at [com.btkelly:gandalf:1.3.0] AndroidManifest.xml:15:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:15:5-19:11 to override.

**Comment by kyhule** [comment] 2016-08-15 20:19
I just stumbled upon this https://code.google.com/p/android/issues/detail?id=193679. Looks like there is a bug in the build tools with no workaround. I believe removing your label should fix the problem. I can submit a pull request with the proposed change.

**Comment by btkelly** [comment] 2016-08-15 20:22
Ah, this is a good catch. This is caused by the fact that you have hard coded the label value inside your application block. I will include a fix for this in the next release, in the meantime you can create a string resource like so `<string name="app_name">ClinicalKey DEBUG</string>` and setting your application label to `android:label="@string/app_name"`.

Great find, thanks for reporting this.

**Comment by btkelly** [comment] 2016-08-15 20:23
Feel free to submit a PR, always appreciate the help.

**Comment by kyhule** [comment] 2016-08-15 20:30
The hardcoded value is on in my debug/AndroidManifest.xml. I get the same error when building release which uses a string resource: 

Attribute application@label value=(@string/clinicalkey_title) from AndroidManifest.xml:20:9-50
	is also present at [com.btkelly:gandalf:1.3.0] AndroidManifest.xml:15:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:15:5-417:19 to override.

**Comment by kyhule** [comment] 2016-08-15 20:31
Seems like the issue is I am using the tools:ignore attribute with the tools:replace and that is the bug in the linked android bug report. Only workaround I have found is removing the tools:ignore attribute.

**Comment by btkelly** [comment] 2016-08-15 20:38
The issue comes from the fact that the label is already defined and cannot be different. If you update your label string resource name to `app_name` instead of `clinicalkey_title` for all build types this should resolve the issue. When the merging occurs it will replace the library version of `app_name` with your version. This is still a work around and I would like to resolve it by removing the label from the lib itself.

**Comment by kyhule** [comment] 2016-08-15 20:51
Ahh, you are right, that did the trick. Thanks! Great work on the library by the way. Working on a prototype to build this into our app and stumbled upon this library. Need to convince the team its worthy of using and hopefully the iOS guys like iOS version as well. Anyway, I am going to submit a PR. Do you think any of that application tag is necessary? Most libraries don't have one at all.

**Comment by btkelly** [comment] 2016-08-15 20:56
Probably not, you can pull everything and just test compilation with the built in example app. If that works fine should be good to go.

**Closed** 2016-08-16 15:00 UTC
Labels: bug
